# Generated by Django 3.2.9 on 2021-12-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libtekticket', '0002_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketnote',
            name='ticket',
            field=models.ForeignKey(default=1, help_text='The ticket to which this note applies', on_delete=django.db.models.deletion.CASCADE, to='libtekticket.ticket'),
            preserve_default=False,
        ),
    ]
