# Generated by Django 3.2.9 on 2021-12-25 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0009_auto_20211225_1451'),
        ('libtekticket', '0003_ticketnote_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The location leave blank if not applicable or you have trouble finding it', null=True, on_delete=django.db.models.deletion.SET_NULL, to='libtekin.location'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='item',
            field=models.ForeignKey(blank=True, help_text='The item to which this ticket applies - leave blank if not applicable you have trouble finding it', null=True, on_delete=django.db.models.deletion.SET_NULL, to='libtekin.item'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='urgency',
            field=models.IntegerField(choices=[(1, '1) Safety Hazard or Work Stoppage'), (2, '2'), (3, '3) Important Issue'), (4, '4'), (5, '5) Minor Issue or Suggestion')], help_text='The urgency, on a scale of 1 to 5, where 1 is the most urgent', verbose_name='Urgency'),
        ),
    ]
