# Generated by Django 3.2.9 on 2021-12-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekticket', '0005_alter_ticket_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution',
            field=models.TextField(blank=True, help_text='How the problem was resolved', verbose_name='Resolution'),
        ),
    ]
