# Generated by Django 3.2.9 on 2021-12-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekticket', '0006_ticket_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='short_description',
            field=models.CharField(default='', help_text='A short description of the issue', max_length=75, verbose_name='Short Description'),
            preserve_default=False,
        ),
    ]
