# Generated by Django 3.2.9 on 2022-01-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekticket', '0008_alter_technician_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketnote',
            name='text',
            field=models.CharField(help_text='The text of the note', max_length=255, verbose_name='text'),
        ),
    ]
