# Generated by Django 3.2.9 on 2022-01-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekticket', '0009_alter_ticketnote_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-when']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='when',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-01', help_text='The date and time the ticket was submitted'),
            preserve_default=False,
        ),
    ]
