# Generated by Django 3.2.9 on 2022-01-02 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libtekticket', '0011_auto_20220102_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketnote',
            name='submitted_by',
            field=models.ForeignKey(help_text='The user who submitted this note', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
    ]
