# Generated by Django 3.2.9 on 2022-01-21 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libtekticket', '0016_alter_ticket_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='submitted_by',
            field=models.ForeignKey(help_text='The user who submitted this ticket', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
    ]
