# Generated by Django 3.2.9 on 2022-01-22 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekticket', '0017_alter_ticket_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='when',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='The date and time the ticket was submitted'),
        ),
        migrations.AlterField(
            model_name='ticketnote',
            name='text',
            field=models.CharField(blank=True, help_text='The text of the note', max_length=255, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='ticketnote',
            name='when',
            field=models.DateField(default=datetime.datetime.now, help_text='The effective date of the note (when it applies as opposed to when it was actually made)', verbose_name='when'),
        ),
    ]
