# Generated by Django 3.2.9 on 2022-02-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0015_auto_20220201_1522'),
        ('libtekticket', '0021_ticket_recipient_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='item',
            field=models.ForeignKey(blank=True, help_text='The item to which this ticket applies - leave blank if not applicable or you have trouble finding it', null=True, on_delete=django.db.models.deletion.SET_NULL, to='libtekin.item'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='recipient_emails',
            field=models.TextField(blank=True, help_text='The comma-separated list of emails of those who should get updates on this ticket.  By default, emails are sent for changes in notes and resolution status', verbose_name='recipient emails'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='urgency',
            field=models.IntegerField(choices=[(1, '1) Safety Hazard or Work Stoppage'), (2, '2) Major Work Impediment'), (3, '3) Highly Important Issue'), (4, '4) Moderately Important Issue'), (5, '5) Minor Issue or Suggestion')], default=4, help_text='The urgency, on a scale of 1 to 5, where 1 is the most urgent', verbose_name='Urgency'),
        ),
    ]
