# Generated by Django 4.1.2 on 2023-01-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekticket', '0022_auto_20220205_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketnote',
            old_name='text',
            new_name='maintext',
        ),
    ]
